title: "Twilio Startups" 
description: "A resource hub for Twilio Startups"

url: "https://twilio.github.io"  # Your site URL
baseurl: "/startups"               # Base URL for your project (leave it empty if it's a root-level site)


remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md

footer: 'learn more about <a href="https://www.twilio.com/en-us/solutions/startups">twilio startups</a>'

style: dark # dark (default) or light

listen_for_clients_preferred_style: true # true or false (default)

